// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // TODO: Replace these with your actual Firebase configuration
  // Run: flutterfire configure --project=sham-coffee
  
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBD3RarLj_696emYW84zZ1tliP_Th1z6mM',
    appId: '1:483086837036:web:2a6bf9084050ef399ef889',
    messagingSenderId: '483086837036',
    projectId: 'sham-coffee',
    authDomain: 'sham-coffee.firebaseapp.com',
    storageBucket: 'sham-coffee.firebasestorage.app',
    databaseURL: 'https://sham-coffee-default-rtdb.firebaseio.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBD3RarLj_696emYW84zZ1tliP_Th1z6mM',
    appId: '1:483086837036:android:sham_coffee_staff',
    messagingSenderId: '483086837036',
    projectId: 'sham-coffee',
    storageBucket: 'sham-coffee.firebasestorage.app',
    databaseURL: 'https://sham-coffee-default-rtdb.firebaseio.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBD3RarLj_696emYW84zZ1tliP_Th1z6mM',
    appId: '1:483086837036:ios:sham_coffee_staff',
    messagingSenderId: '483086837036',
    projectId: 'sham-coffee',
    storageBucket: 'sham-coffee.firebasestorage.app',
    databaseURL: 'https://sham-coffee-default-rtdb.firebaseio.com',
    iosBundleId: 'com.shamcoffee.staff',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBD3RarLj_696emYW84zZ1tliP_Th1z6mM',
    appId: '1:483086837036:ios:sham_coffee_staff',
    messagingSenderId: '483086837036',
    projectId: 'sham-coffee',
    storageBucket: 'sham-coffee.firebasestorage.app',
    databaseURL: 'https://sham-coffee-default-rtdb.firebaseio.com',
    iosBundleId: 'com.shamcoffee.staff',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBD3RarLj_696emYW84zZ1tliP_Th1z6mM',
    appId: '1:483086837036:web:2a6bf9084050ef399ef889',
    messagingSenderId: '483086837036',
    projectId: 'sham-coffee',
    authDomain: 'sham-coffee.firebaseapp.com',
    storageBucket: 'sham-coffee.firebasestorage.app',
    databaseURL: 'https://sham-coffee-default-rtdb.firebaseio.com',
  );
}





